RoyayaControlPanel.com/Models/ContactUs.cs
using Newtonsoft.Json;
using Royaya.com.Extras;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Royaya.com.Models
{
    public class ContactUs:BasicModel
    {
        [Required]
        [Display(Name = "Message")]
        public string Message { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Job Description")]
        public string JobDescription { get; set; }

        [Required]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        [Display(Name = "Response")]
        public string Response { get; set; }

    }
}

RoyayaControlPanel.com/Controllers/ContactUsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Royaya.com.Models;
using RoyayaControlPanel.com.Models;
using RoyayaControlPanel.com.ViewModels;

namespace RoyayaControlPanel.com.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ContactUsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ContactUs
        public async Task<ActionResult> Index()
        {
            List<ContactUs> list = db.ContactUss.ToList();
            List<ApplicationUser> users = db.Users.ToList();
            List<ContactUsViewModel> result = new List<ContactUsViewModel>();
            foreach (var item in list)
            {
                ContactUsViewModel temp = new ContactUsViewModel();
                temp.id = item.id;
                temp.creatorId = item.Creator;
                temp.Email = item.Email;
                temp.JobDescription = item.JobDescription;
                temp.PhoneNumber = item.PhoneNumber;
                temp.Name = item.Name;
                temp.CreationDate = item.CreationDate;
                temp.Message = item.Message;
                temp.Status = item.Status;
                temp.creatorName = users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault() != null ? users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault().Name : "";
                ApplicationUser interpreter = db.Users.Where(a => a.PhoneNumber.Equals(item.PhoneNumber)).FirstOrDefault();
                if (interpreter != null)
                {
                    temp.interpreterName = interpreter.Name;
                    temp.interpreterId = interpreter.Id;
                }
                else {
                    temp.interpreterName = "";
                    temp.interpreterId = "";
                }
                result.Add(temp);
            }
            
            return View(result);
        }

        // GET: ContactUs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactUs contactUs = await db.ContactUss.FindAsync(id);
            if (contactUs == null)
            {
                return HttpNotFound();
            }
            return View(contactUs);
        }

        // GET: ContactUs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ContactUs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,Message,Email,Name,JobDescription,PhoneNumber,CreationDate,LastModificationDate,Creator,Modifier,AttachmentId")] ContactUs contactUs)
        {
            if (ModelState.IsValid)
            {
                db.ContactUss.Add(contactUs);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(contactUs);
        }

        // GET: ContactUs/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactUs contactUs = await db.ContactUss.FindAsync(id);
            if (contactUs == null)
            {
                return HttpNotFound();
            }
            return View(contactUs);
        }

        // POST: ContactUs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,Message,Email,Name,JobDescription,PhoneNumber,CreationDate,LastModificationDate,Creator,Modifier,AttachmentId")] ContactUs contactUs)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contactUs).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(contactUs);
        }
        [HttpPost]
        public JsonResult addResponse(int id, string message) {
            ContactUs item = db.ContactUss.Find(id);
            item.Message = message;
            item.LastModificationDate = DateTime.Now;
            db.Entry(item).State = EntityState.Modified;
            db.SaveChanges();
            return Json(item, JsonRequestBehavior.AllowGet);
        }
        // GET: ContactUs/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ContactUs contactUs = await db.ContactUss.FindAsync(id);
            if (contactUs == null)
            {
                return HttpNotFound();
            }
            return View(contactUs);
        }

        // POST: ContactUs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ContactUs contactUs = await db.ContactUss.FindAsync(id);
            db.ContactUss.Remove(contactUs);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RoyayaControlPanel.com/Controllers/DreamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Royaya.com.Models;
using RoyayaControlPanel.com.Models;
using PagedList;
using RoyayaControlPanel.com.ViewModels;

namespace RoyayaControlPanel.com.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DreamsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Dreams
        public async Task<ActionResult> Index(int? page, string searchString, string status)
        {
            var users = db.Users;
            var dreams = db.Dreams.Include(d => d.interpretator).Include(d => d.path).OrderByDescending(r => r.CreationDate);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            if (searchString != null && !searchString.Equals(""))
                dreams = dreams.Where(a => a.Description.Contains(searchString)).OrderByDescending(r => r.CreationDate);
            if (status != null && !status.Equals(""))
                dreams = dreams.Where(a => a.Status.Equals(status)).OrderByDescending(r => r.CreationDate);
            //dreams = dreams.Skip((pageNumber-1)*pageSize).Take(pageSize).ToList();
            List<DreamViewModel> dreamsView = new List<DreamViewModel>();
            foreach (var item in dreams)
            {
                DreamViewModel temp = new DreamViewModel
                {
                    id = item.id,
                    CreatorId = item.Creator,

                    //temp.CreatorName = users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault()!=null?users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault().Name:"";
                    Description = item.Description,
                    Explanation = item.Explanation,
                    ExplanationDate = item.ExplanationDate,
                    InterpretationStartDate = item.InterpretationStartDate,
                    interpretatorId = item.interpretatorId != null ? item.interpretatorId : "",
                    interpretatorName = item.interpretator != null ? item.interpretator.Name : "",
                    pathCost = item.path != null ? item.path.Cost : -1,
                    pathId = item.pathId != null ? item.pathId : 0,
                    RatingDate = item.RatingDate,
                    Status = item.Status,
                    UserRating = item.UserRating,
                    CreationDate = item.CreationDate
                };
                dreamsView.Add(temp);
            }
            return View(dreamsView.ToPagedList(pageNumber, pageSize));
        }

        [AllowAnonymous]
        [HttpGet]
        public JsonResult GetDreams(string searchString,string status, int page)
        {
            var users = db.Users;
            var dreams = db.Dreams.Include(d => d.interpretator).Include(d => d.path).OrderByDescending(r => r.CreationDate);
            int pageSize = 10;
            int pageNumber = (page == 0 || page == null) ? 1: page;
            if (searchString != null && !searchString.Equals(""))
                dreams = dreams.Where(a => a.Description.Contains(searchString)).OrderByDescending(r => r.CreationDate);
            if (status != null && !status.Equals(""))
                dreams = dreams.Where(a => a.Status.Equals(status)).OrderByDescending(r => r.CreationDate);
            dreams = dreams.Skip((pageNumber-1)*pageSize).Take(pageSize).OrderByDescending(r => r.CreationDate); ;
            List<DreamViewModel> dreamsView = new List<DreamViewModel>();
            foreach (var item in dreams)
            {
                item.numberOfViews++;
                db.Entry(item).State = EntityState.Modified;
                DreamViewModel temp = new DreamViewModel
                {
                    id = item.id,
                    CreatorId = item.Creator,

                    //temp.CreatorName = users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault()!=null?users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault().Name:"";
                    Description = item.Description,
                    Explanation = item.Explanation,
                    ExplanationDate = item.ExplanationDate,
                    InterpretationStartDate = item.InterpretationStartDate,
                    interpretatorId = item.interpretatorId != null ? item.interpretatorId : "",
                    interpretatorName = item.interpretator != null ? item.interpretator.Name : "",
                    pathCost = item.path != null ? item.path.Cost : -1,
                    pathId = item.pathId != null ? item.pathId : 0,
                    RatingDate = item.RatingDate,
                    Status = item.Status,
                    UserRating = item.UserRating,
                    CreationDate = item.CreationDate,
                    numberOfLikes=item.numberOfLikes,
                    numberOfViews=item.numberOfViews,
                    
                    AllItems = dreams.Count()
                };
                dreamsView.Add(temp);
            }
            db.SaveChanges();
            //return Json(dreamsView.ToPagedList(pageNumber, pageSize),JsonRequestBehavior.AllowGet);
            return Json(dreamsView, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public JsonResult GetSingleDream(int? id)
        {
            
            Dream item = db.Dreams.Find(id);

            DreamViewModel temp = new DreamViewModel();
            temp.CreatorId = item.Creator;

            //temp.CreatorName = users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault()!=null?users.Where(a => a.Id.Equals(item.Creator)).FirstOrDefault().Name:"";
            temp.Description = item.Description;
            temp.Explanation = item.Explanation;
            temp.ExplanationDate = item.ExplanationDate;
            temp.InterpretationStartDate = item.InterpretationStartDate;
            temp.interpretatorId = item.interpretatorId != null ? item.interpretatorId : "";
            temp.interpretatorName = item.interpretator != null ? item.interpretator.Name : "";
            temp.pathCost = item.path != null ? item.path.Cost : -1;
            temp.pathId = item.pathId != null ? item.pathId : 0;
            temp.RatingDate = item.RatingDate;
            temp.Status = item.Status;
            temp.UserRating = item.UserRating;
            temp.CreationDate = item.CreationDate;
            return Json(temp, JsonRequestBehavior.AllowGet);
        }

        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dream dream = await db.Dreams.FindAsync(id);
            if (dream == null)
            {
                return HttpNotFound();
            }
            return View(dream);
        }

        [AllowAnonymous]
        public async Task<ActionResult> DreamPage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dream dream = await db.Dreams.FindAsync(id);
            if (dream == null)
            {
                return HttpNotFound();
            }

            dream.numberOfViews++;
            db.Entry(dream).State = EntityState.Modified;
            db.SaveChanges();

            ApplicationUser creator = db.Users.Where(a => a.Id.Equals(dream.Creator)).FirstOrDefault();
            ApplicationUser Interpreter = db.Users.Where(a => a.Id.Equals(dream.interpretatorId)).FirstOrDefault();
            InterprationPath path = db.InterprationPaths.Where(a => a.id.Equals(dream.pathId)).FirstOrDefault();
            if (path.Cost == 0)
                ViewBag.Type = "رؤية مجانية";
            else
                ViewBag.Type = "رؤية مدفوعة";

            ViewBag.InterpreterName = Interpreter != null ? Interpreter.Name : "";
            ViewBag.CreatorName = creator != null ? creator.Name : "";
            return View(dream);
        }

        // GET: Dreams/Create
        public ActionResult Create()
        {
            ViewBag.interpretatorId = new SelectList(db.Users.Where(a => a.Type.Equals("Interpreter")), "Id", "Name");
            ViewBag.pathId = new SelectList(db.InterprationPaths, "id", "Cost");
            return View();
        }

        // POST: Dreams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,Status,Description,interpretatorId,pathId,Explanation,ExplanationDate,UserRating,RatingDate,InterpretationStartDate,CreationDate,LastModificationDate,Creator,Modifier,AttachmentId")] Dream dream)
        {
            if (ModelState.IsValid)
            {
                dream.CreationDate = DateTime.Now;
                dream.LastModificationDate = DateTime.Now;
                db.Dreams.Add(dream);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.interpretatorId = new SelectList(db.Users, "Id", "Sex", dream.interpretatorId);
            ViewBag.pathId = new SelectList(db.InterprationPaths, "id", "Status", dream.pathId);
            return View(dream);
        }

        // GET: Dreams/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dream dream = await db.Dreams.FindAsync(id);
            if (dream == null)
            {
                return HttpNotFound();
            }

RoyayaControlPanel.com/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>
@section Scripts
{
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

}

RoyayaControlPanel.com/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

RoyayaControlPanel.com/Views/Home/ContactUs.cshtml
@{
    Layout = "~/Views/Shared/_empty.cshtml";
    ViewBag.Title = "Contact Us";
}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="~/MainPageStyle/css/style.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/MainPageStyle/css/fontawesome.css">
    <link rel="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <style>


        .bg-light {
            background-color: unset !important;
        }
        .navbar {
            position: absolute;
            top: 5px;
        }
    </style>
    <link rel="shortcut icon" href="~/MainPageStyle/img/asset-5.png">

</head>
<body>
    <img class="img img-fluid" src="~/MainPageStyle/img/others.svg" />
    @*<nav class="navbar navbar-expand-lg navbar-light bg-light" style="width: fit-content;">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link text-white" href="@Url.Action("Main", "Home")" style="margin-top: 1px"><span class="ml-1 align-middle"><svg class="svg-inline--fa fa-home fa-w-18 fa-2x" style="height: 30.9px !important;width: 36.4px !important;" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="home" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512" data-fa-i2svg=""><path fill="currentColor" d="M280.37 148.26L96 300.11V464a16 16 0 0 0 16 16l112.06-.29a16 16 0 0 0 15.92-16V368a16 16 0 0 1 16-16h64a16 16 0 0 1 16 16v95.64a16 16 0 0 0 16 16.05L464 480a16 16 0 0 0 16-16V300L295.67 148.26a12.19 12.19 0 0 0-15.3 0zM571.6 251.47L488 182.56V44.05a12 12 0 0 0-12-12h-56a12 12 0 0 0-12 12v72.61L318.47 43a48 48 0 0 0-61 0L4.34 251.47a12 12 0 0 0-1.6 16.9l25.5 31A12 12 0 0 0 45.15 301l235.22-193.74a12.19 12.19 0 0 1 15.3 0L530.9 301a12 12 0 0 0 16.9-1.6l25.5-31a12 12 0 0 0-1.7-16.93z"></path></svg></span>الرئيسية </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="@Url.Action("ContactUs", "Home")"><span class="ml-1 align-middle"><svg class="svg-inline--fa fa-envelope fa-w-16 fa-2x" style="height: 27.7px !i;width: 34.7px !important;" aria-hidden="true" focusable="false" data-prefix="far" data-icon="envelope" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg=""><path fill="currentColor" d="M464 64H48C21.49 64 0 85.49 0 112v288c0 26.51 21.49 48 48 48h416c26.51 0 48-21.49 48-48V112c0-26.51-21.49-48-48-48zm0 48v40.805c-22.422 18.259-58.168 46.651-134.587 106.49-16.841 13.247-50.201 45.072-73.413 44.701-23.208.375-56.579-31.459-73.413-44.701C106.18 199.465 70.425 171.067 48 152.805V112h416zM48 400V214.398c22.914 18.251 55.409 43.862 104.938 82.646 21.857 17.205 60.134 55.186 103.062 54.955 42.717.231 80.509-37.199 103.053-54.947 49.528-38.783 82.032-64.401 104.947-82.653V400H48z"></path></svg></span><span>اتصل بنا</span></a>
            </li>
        </ul>
    </nav>*@
    <img class="rounded" src="~/MainPageStyle/img/Group 1698.svg" style="width:327px ;height:106px;margin-left: 506px;margin-top: 86px;" />
    <div class="contact-info d-flex  flex-column bd-highlight m-4 p-4" style="margin-right: 117px !important;">
        <div class="phone text-blue">
            <a href="https://play.google.com/store/apps/details?id=com.fsrhilmk.fsrhilmkapp"><span><img src="~/MainPageStyle/img/google-play.png"></span>
            <span class="mr-4">Google Play</span>
            <hr class="mr-4">
            </a>
        </div>
        <div class="email text-blue">
            <span><img src="~/MainPageStyle/img/app-store.png"></span>
            <span class="mr-4">Apple Store</span>
            <hr class="mr-4">
        </div>

    </div>

</body>
@section Scripts
{
    <script src="~/MainPageStyle/js/fontawesome.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    
}

RoyayaControlPanel.com/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_PLayout.cshtml";
}

<div class="jumbotron">
    <h1>@Resources.Global.Statistics</h1>
    <p class="lead">
        <div class="row" style="font-size:large">
            <div class="col-md-6 col-sm-6 "><span> @Resources.Global.All_Users: </span> <span id="AllUsers"> value</span></div>
            <div class="col-md-6 col-sm-6"><span> @Resources.Global.Admins: </span> <span id="Admins"> value</span></div>
        </div>
        <div class="row " style="font-size:large">
            <div class="col-md-6 col-sm-6 "><span> @Resources.Global.Clients: </span> <span id="Clients"> value</span></div>
            <div class="col-md-6 col-sm-6"><span> @Resources.Global.Interpreters: </span> <span id="Interpreters"> value</span></div>
        </div>
        <div class="row" style="font-size:large">
            <div class="col-md-6 col-sm-6 "><span> @Resources.Global.All_Dreams: </span> <span id="AllDreams"> value</span></div>
            <div class="col-md-6 col-sm-6"><span> @Resources.Global.Active_dreams: </span> <span id="ActiveDreams"> value</span></div>
        </div>
        <div class="row" style="font-size:large">
            <div class="col-md-6 col-sm-6 "><span> @Resources.Global.Done_dreams: </span> <span id="DoneDreams"> value</span></div>
            <div class="col-md-6 col-sm-6 "><span> @Resources.Global.OnlineUsers: </span> <span id="onlineUsers"> value</span></div>
        </div>
    </p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Dreams List</h2>
        <p><a class="btn btn-default" href="@Url.Action("Index","Dreams")">@Resources.Global.Dreams &raquo;</a></p>
        <p><a class="btn btn-default" href="@Url.Action("Create","Dreams")">@Resources.Global.Add_dream &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Interpretation Paths</h2>
        <p><a class="btn btn-default" href="@Url.Action("Index","InterprationPaths")">@Resources.Global.Interpretation_Paths &raquo;</a></p>
        <p><a class="btn btn-default" href="@Url.Action("Create","InterprationPaths")">@Resources.Global.Add_path &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Interpreters</h2>
        <p><a class="btn btn-default" href="@Url.Action("Interpreters","Account")">@Resources.Global.Interpreters &raquo;</a></p>
    </div>
</div>

@section Scripts
{
<script type="text/javascript">
    $(document).ready(function () {
        WorkExperienceLoadData();

    });
    function WorkExperienceLoadData() {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("getAllStatistics", "Account")',
            dataType: 'json',
            data: {},
            success: function (data) {
            var items = '';
            $('#AllDreams').text(data.AllDreams);
            $('#ActiveDreams').text(data.allActiveDreams);
            $('#DoneDreams').text(data.allDoneDreams);
            $('#Interpreters').text(data.allInterpreters);
            $('#Clients').text(data.allClients);
            $('#Admins').text(data.allAdmins);
            $('#AllUsers').text(data.allUsers);
            $('#onlineUsers').text(data.onlineUsers);
            


            //$.each(data, function (i, item) {
            //var from_date = item.From;
            //var to_date = item.To;
            //var from =  new Date(parseInt(from_date.substr(6)));
            //var to = new Date(parseInt(to_date.substr(6)))

            //$('#AllDreams').

            //});
            },
            error: function (ex) {
            var r = jQuery.parseJSON(response.responseText);
            alert("Message: " + r.Message);
            alert("StackTrace: " + r.StackTrace);
            alert("ExceptionType: " + r.ExceptionType);
            }
            });
            return false;
       }
    </script>
    }