RoyayaControlPanel.com/Models/PublicInterpreterRatio.cs
using Royaya.com.Extras;
using Royaya.com.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RoyayaControlPanel.com.Models
{
    public class PublicInterpreterRatio : BasicModel
    {

        public double ratio { get; set; }

        public int pathId { get; set; }


        public InterprationPath path { get; set; }
    }
}

RoyayaControlPanel.com/Controllers/PublicInterpreterRatiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RoyayaControlPanel.com.Models;

namespace RoyayaControlPanel.com.Controllers
{
    public class PublicInterpreterRatiosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: PublicInterpreterRatios
        public ActionResult Index()
        {
            var publicInterpreterRatios = db.PublicInterpreterRatios.Include(p => p.path);
            return View(publicInterpreterRatios.ToList());
        }

        // GET: PublicInterpreterRatios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PublicInterpreterRatio publicInterpreterRatio = db.PublicInterpreterRatios.Find(id);
            if (publicInterpreterRatio == null)
            {
                return HttpNotFound();
            }
            return View(publicInterpreterRatio);
        }

        // GET: PublicInterpreterRatios/Create
        public ActionResult Create()
        {
            ViewBag.pathId = new SelectList(db.InterprationPaths, "id", "Cost");
            return View();
        }

        // POST: PublicInterpreterRatios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( PublicInterpreterRatio publicInterpreterRatio)
        {
            if (ModelState.IsValid)
            {
                publicInterpreterRatio.CreationDate = DateTime.Now;
                publicInterpreterRatio.LastModificationDate = DateTime.Now;
                db.PublicInterpreterRatios.Add(publicInterpreterRatio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.pathId = new SelectList(db.InterprationPaths, "id", "Status", publicInterpreterRatio.pathId);
            return View(publicInterpreterRatio);
        }

        // GET: PublicInterpreterRatios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PublicInterpreterRatio publicInterpreterRatio = db.PublicInterpreterRatios.Find(id);
            if (publicInterpreterRatio == null)
            {
                return HttpNotFound();
            }
            ViewBag.pathId = new SelectList(db.InterprationPaths, "id", "Cost", publicInterpreterRatio.pathId);
            return View(publicInterpreterRatio);
        }

        // POST: PublicInterpreterRatios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( PublicInterpreterRatio publicInterpreterRatio)
        {
            if (ModelState.IsValid)
            {
                PublicInterpreterRatio temp = db.PublicInterpreterRatios.Find(publicInterpreterRatio.id);
                temp.LastModificationDate = DateTime.Now;
                db.Entry(publicInterpreterRatio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.pathId = new SelectList(db.InterprationPaths, "id", "Status", publicInterpreterRatio.pathId);
            return View(publicInterpreterRatio);
        }

        // GET: PublicInterpreterRatios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PublicInterpreterRatio publicInterpreterRatio = db.PublicInterpreterRatios.Find(id);
            if (publicInterpreterRatio == null)
            {
                return HttpNotFound();
            }
            return View(publicInterpreterRatio);
        }

        // POST: PublicInterpreterRatios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PublicInterpreterRatio publicInterpreterRatio = db.PublicInterpreterRatios.Find(id);
            db.PublicInterpreterRatios.Remove(publicInterpreterRatio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RoyayaControlPanel.com/Views/PublicInterpreterRatios/Create.cshtml
@model RoyayaControlPanel.com.Models.PublicInterpreterRatio

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_PLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PublicInterpreterRatio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ratio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ratio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ratio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pathId, "pathId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("pathId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pathId, "", new { @class = "text-danger" })
            </div>
        </div>




   

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoyayaControlPanel.com/Views/PublicInterpreterRatios/Delete.cshtml
@model RoyayaControlPanel.com.Models.PublicInterpreterRatio

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_PLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PublicInterpreterRatio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.path.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.path.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ratio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ratio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModificationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModificationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modifier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modifier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AttachmentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttachmentId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RoyayaControlPanel.com/Views/PublicInterpreterRatios/Details.cshtml
@model RoyayaControlPanel.com.Models.PublicInterpreterRatio

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_PLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>PublicInterpreterRatio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.path.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.path.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ratio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ratio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastModificationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastModificationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modifier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modifier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AttachmentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttachmentId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RoyayaControlPanel.com/Views/PublicInterpreterRatios/Edit.cshtml
@model RoyayaControlPanel.com.Models.PublicInterpreterRatio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_PLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PublicInterpreterRatio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.ratio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ratio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ratio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.pathId, "pathId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("pathId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.pathId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastModificationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastModificationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastModificationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Creator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Creator, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Creator, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modifier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modifier, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modifier, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AttachmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AttachmentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttachmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RoyayaControlPanel.com/Views/PublicInterpreterRatios/Index.cshtml
@model IEnumerable<RoyayaControlPanel.com.Models.PublicInterpreterRatio>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PLayout.cshtml";
}

<h2>@Resources.Global.RatioForEachPath</h2>


<div style="float:right;" class="col-md-12">
    <button style="float:right;" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "PublicInterpreterRatios")'">
        @Resources.Global.AddNewRatio
    </button>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.path.Cost)
        </th>
        <th>
            @Resources.Global.Ratio
        </th>
        <th>
            @Resources.Dream.CreationDate
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastModificationDate)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.path.Cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ratio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastModificationDate)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |*@
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>